# Generated by Django 5.0 on 2023-12-20 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('platform', models.CharField(default='sleeper', max_length=100)),
                ('are_managers_imported', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('conference', models.CharField(max_length=3, null=True)),
                ('division', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_user_id', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fantasy_teams', to='side_bets.fantasyleague')),
            ],
            options={
                'unique_together': {('sleeper_user_id', 'league')},
            },
        ),
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_id', models.CharField(max_length=30, unique=True)),
                ('espn_id', models.CharField(max_length=30, unique=True)),
                ('yahoo_id', models.CharField(max_length=30, unique=True)),
                ('nfl_id', models.CharField(max_length=30, unique=True)),
                ('fantasypros_id', models.CharField(max_length=30)),
                ('fantasy_data_id', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=10)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='side_bets.nflteam')),
            ],
        ),
        migrations.CreateModel(
            name='NFLGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50, unique=True)),
                ('away_score', models.IntegerField()),
                ('away_result', models.CharField(max_length=5)),
                ('home_score', models.IntegerField()),
                ('home_result', models.CharField(max_length=5)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('game_week', models.IntegerField()),
                ('scores_imported', models.BooleanField()),
                ('season', models.IntegerField()),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='side_bets.nflteam')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='side_bets.nflteam')),
            ],
        ),
        migrations.CreateModel(
            name='FantasyRosterWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_week', models.IntegerField()),
                ('starters', models.CharField(max_length=1000)),
                ('bench', models.CharField(max_length=1000)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='side_bets.fantasyleague')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='side_bets.fantasyteam')),
            ],
            options={
                'unique_together': {('league', 'game_week', 'team')},
            },
        ),
        migrations.CreateModel(
            name='NFLBoxscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_tds', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('carries', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('passing_completions', models.IntegerField()),
                ('passing_ints', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('targets', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('fumbles_lost', models.IntegerField()),
                ('fantasy_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxscores', to='side_bets.fantasyteam')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxscores', to='side_bets.nflgame')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxscores', to='side_bets.nflplayer')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
    ]
