# Generated by Django 5.0 on 2023-12-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fantasyleague',
            old_name='are_managers_imported',
            new_name='are_teams_imported',
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='are_users_imported',
            field=models.BooleanField(default=False),
        ),
    ]
