# Generated by Django 5.0 on 2023-12-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('managers_imported', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FantasyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_teams', to='side_bets.fantasyleague')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_teams', to='side_bets.fantasymanager')),
            ],
        ),
        migrations.CreateModel(
            name='NFLBoxscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_tds', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('carries', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('passing_completions', models.IntegerField()),
                ('passing_ints', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('targets', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('fumbles_lost', models.IntegerField()),
                ('fantasy_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxscores', to='side_bets.fantasyteam')),
            ],
        ),
        migrations.CreateModel(
            name='NFLGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50, unique=True)),
                ('away_score', models.IntegerField()),
                ('away_result', models.CharField(max_length=5)),
                ('home_score', models.IntegerField()),
                ('home_result', models.CharField(max_length=5)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('game_week', models.IntegerField()),
                ('scores_imported', models.BooleanField()),
                ('season', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_id', models.CharField(max_length=30, unique=True)),
                ('espn_id', models.CharField(max_length=30, unique=True)),
                ('yahoo_id', models.CharField(max_length=30, unique=True)),
                ('nfl_id', models.CharField(max_length=30, unique=True)),
                ('fantasypros_id', models.CharField(max_length=30)),
                ('fantasy_data_id', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='nflboxscore',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxscores', to='side_bets.nflgame'),
        ),
        migrations.AddField(
            model_name='nflboxscore',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxscores', to='side_bets.nflplayer'),
        ),
        migrations.AddField(
            model_name='nflplayer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='side_bets.nflteam'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='side_bets.nflteam'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='side_bets.nflteam'),
        ),
        migrations.AlterUniqueTogether(
            name='nflboxscore',
            unique_together={('player', 'game')},
        ),
    ]
