# Generated by Django 5.0 on 2023-12-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0002_fantasyleague_fantasymanager_fantasyteam_nflboxscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='conference',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='division',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
