# Generated by Django 5.0 on 2023-12-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0002_rename_are_managers_imported_fantasyleague_are_teams_imported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='roster_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to='side_bets.fantasyleague'),
        ),
    ]
