# Generated by Django 5.0 on 2023-12-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0003_fantasyteam_roster_id_alter_fantasyteam_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrosterweek',
            name='matchup_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fantasyrosterweek',
            name='roster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyrosterweek',
            name='bench',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyrosterweek',
            name='game_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyrosterweek',
            name='starters',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='roster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
