# Generated by Django 5.0 on 2023-12-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0004_remove_fantasyrosterweek_opponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflteam',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='nflteam',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
