# Generated by Django 5.0 on 2023-12-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0005_remove_nflteam_short_name_alter_nflteam_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflgame',
            old_name='game_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='nflgame',
            old_name='game_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='nflgame',
            old_name='game_week',
            new_name='week',
        ),
        migrations.RemoveField(
            model_name='nflgame',
            name='game_id',
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
