# Generated by Django 5.0 on 2023-12-31 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0007_remove_fantasyleague_season_remove_nflgame_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLSeason',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fantasy_leagues', to='side_bets.nflseason'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='side_bets.nflseason'),
        ),
    ]
