# Generated by Django 5.0 on 2024-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0008_nflseason_fantasyleague_season_nflgame_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflseason',
            name='are_games_imported',
            field=models.BooleanField(default=False),
        ),
    ]
