# Generated by Django 5.0 on 2024-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0009_nflseason_are_games_imported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fantasyleague',
            options={'verbose_name': 'Fantasy League', 'verbose_name_plural': 'Fantasy Leagues'},
        ),
        migrations.AlterModelOptions(
            name='fantasyrosterweek',
            options={'verbose_name': 'Fantasy Roster Week', 'verbose_name_plural': 'Fantasy Roster Weeks'},
        ),
        migrations.AlterModelOptions(
            name='fantasyteam',
            options={'verbose_name': 'Fantasy Team', 'verbose_name_plural': 'Fantasy Teams'},
        ),
        migrations.AlterModelOptions(
            name='nflboxscore',
            options={'verbose_name': 'NFL Boxscore', 'verbose_name_plural': 'NFL Boxscores'},
        ),
        migrations.AlterModelOptions(
            name='nflgame',
            options={'verbose_name': 'NFL Game', 'verbose_name_plural': 'NFL Games'},
        ),
        migrations.AlterModelOptions(
            name='nflplayer',
            options={'verbose_name': 'NFL Player', 'verbose_name_plural': 'NFL Players'},
        ),
        migrations.AlterModelOptions(
            name='nflseason',
            options={'verbose_name': 'NFL Season', 'verbose_name_plural': 'NFL Seasons'},
        ),
        migrations.AlterModelOptions(
            name='nflteam',
            options={'verbose_name': 'NFL Team', 'verbose_name_plural': 'NFL Teams'},
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='away_result',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='home_result',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
