# Generated by Django 5.0 on 2024-01-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0011_nflseason_year_alter_nflseason_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyrosterweek',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roster_weeks', to='side_bets.fantasyleague'),
        ),
        migrations.AlterField(
            model_name='fantasyrosterweek',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roster_weeks', to='side_bets.fantasyteam'),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
