# Generated by Django 5.0 on 2024-01-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0013_remove_nflgame_scores_imported_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflboxscore',
            name='fantasy_team',
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='carries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='fumbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='fumbles_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='passing_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='passing_ints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='passing_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='passing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='receiving_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='receptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='rushing_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='rushing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflboxscore',
            name='targets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='espn_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='fantasy_data_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='fantasypros_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='nfl_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='sleeper_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='side_bets.nflteam'),
        ),
        migrations.AlterField(
            model_name='nflplayer',
            name='yahoo_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
