# Generated by Django 5.0 on 2024-01-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0014_remove_nflboxscore_fantasy_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflplayer',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nflplayer',
            name='rotowire_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nflplayer',
            name='rotoworld_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nflplayer',
            name='swish_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
