# Generated by Django 5.0 on 2024-01-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0016_alter_nflboxscore_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nflboxscore',
            unique_together=set(),
        ),
    ]
