# Generated by Django 5.0 on 2024-01-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0018_alter_nflboxscore_game_alter_nflboxscore_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflboxscore',
            name='player',
        ),
        migrations.AddField(
            model_name='nflboxscore',
            name='player_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
