# Generated by Django 5.0.2 on 2024-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0019_remove_nflboxscore_player_nflboxscore_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflseason',
            name='year',
        ),
        migrations.AlterField(
            model_name='nflseason',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
