# Generated by Django 5.0.2 on 2024-05-11 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_bets', '0021_alter_fantasyrosterweek_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflboxscore',
            name='game',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxscores', to='side_bets.nflgame'),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='side_bets.nflteam'),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='side_bets.nflteam'),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='side_bets.nflseason'),
        ),
    ]
